# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:

    # These are the most critical checks.
    #
    - id: check-ast
    - id: flake8

    # Some basic sanitization.
    #
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: double-quote-string-fixer
    - id: check-docstring-first
    - id: mixed-line-ending
      args: [--fix=lf]
    - id: debug-statements

    # Checking data formats.
    #
    - id: check-yaml
    - id: check-json
    - id: check-toml
    - id: check-xml

    # Check for secrets.
    #
    # - id: check-private-key
    # - id: detect-aws-credentials

    # Try to catch some faux-pas.
    #
    # - id: no-commit-to-branch
    #   args: [--branch, master]
    - id: check-added-large-files
      args: [--maxkb=1000]
    - id: check-merge-conflict
    - id: check-symlinks

    # Try to catch some more obscure things.
    #
    - id: check-executables-have-shebangs
    - id: check-byte-order-marker
    - id: check-case-conflict
    - id: fix-encoding-pragma
      args: [--remove]

    # This checks that all links to our VCS are permalinks. How oddly specific!
    - id: check-vcs-permalinks
  - repo: https://github.com/asottile/pyupgrade
    rev: v1.26.1
    hooks:
    - id: pyupgrade
  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.4
    hooks:
    - id: seed-isort-config
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21  # pick the isort version you'd like to use from https://github.com/pre-commit/mirrors-isort/releases
    hooks:
    - id: isort
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
  - repo: https://github.com/mgedmin/check-manifest
    rev: '0.40'
    hooks:
    - id: check-manifest
